/*
* AUTOGENERATED FILE 
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))= 
        "****************"  // placeholder for beggining
        "20250513T215653"   // DateTime using ISO-8601 format
        " "                 // alignment
        "d72000fa"          // STLIB commit
        "--------"          // ADJ commit
        "a9f7024e"          // Board commit
        // the '=' is used for unparsing
        ;
}