/*
* AUTOGENERATED FILE 
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))= 
        "****************"  // placeholder for beggining
        "20250415T211206"   // DateTime using ISO-8601 format
        " "                 // alignment
        "edae7a8e"          // STLIB commit
        "--------"          // ADJ commit
        "aeb4ce58"          // Board commit
        // the '=' is used for unparsing
        ;
}