/*
* AUTOGENERATED FILE 
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))= 
        "****************"  // placeholder for beggining
        "20250503T160810"   // DateTime using ISO-8601 format
        " "                 // alignment
        "d8ec77ae"          // STLIB commit
        "--------"          // ADJ commit
        "945cb612"          // Board commit
        // the '=' is used for unparsing
        ;
}